package;

import flixel.FlxGame;
import openfl.display.Sprite;

class Main extends Sprite
{
	public function new()
	{
		super();
		addChild(new FlxGame(0, 0, PlayState));
	}
	// MMMMMMMMMMMMMMMMMMMMMMMMMWWWNNXXXKKKKKKKKKKKKKKKKXXXNNWWWMMMMMMMMMMMMMMMMMMMMMMMMM
	// MMMMMMMMMMMMMMMMMMMMMWWNXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXNWWMMMMMMMMMMMMMMMMMMMMM
	// MMMMMMMMMMMMMMMMMMWNXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXNWWMMMMMMMMMMMMMMMMM
	// MMMMMMMMMMMMMMMWNXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXNWMMMMMMMMMMMMMMM
	// MMMMMMMMMMMMWWXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0OxdooodxkO0KKKKKKXWMMMMMMMMMMMMM
	// MMMMMMMMMMWNXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK00koc;,''''',,:coxO0KKKKXNWMMMMMMMMMM
	// MMMMMMMMWWXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0Odc;'''''''''''''',:lxO0KKKXWWMMMMMMMM
	// MMMMMMMWNKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKkc,'''',;loddlc;,''''',:ok0KKKNWMMMMMMM
	// MMMMMMNXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKk:''';cdO0KKKK0Oxo:,''''';lk0KKXNMMMMMM
	// MMMMWNKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0kdodk0KKKKKKKKKK0Oxl;,'''';d0KKKNWMMMM
	// MMMWNKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0Oo;''',o0KKKKNWMMM
	// MMWNKKKKKKKKKKK0OkxdoollllloodxkO0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0kdooxOKKKKKKNWMM
	// MWNKKKKKKKKKKKkl;,,''''''''''',,:coxO0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKNWM
	// MNKKKKKKKKKKKKkc,,,;:cclllcc:;,'''',:x0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKNM
	// WXKKKKKKKKKKKK0OxxkO000000000Okdoc;;:x0KKKKKKKKKKKK0Oxdddk0KKKKKKKKKKKKKKKKKKKKKXW
	// NKKKKKKKKKKKKKKKKKKKKK0OxolooxOKK0OkO0KKKKKKKKKKKKOo:,''';lk0KKKKKKKKKKKKKKKKKKKKN
	// XKKKKKKKKKKKKKKKKKKKKOo:,'''',cx0KKKKKKKKKKKKKKKKOl,''''''':k0KKKKKKKKKKKKKKKKKKKX
	// KKKKKKKKKKKKKKKKKKKK0o,'''''''':x0KKKKKKKKKKKKKK0d;'''''''',lOKKKKKKKKKKKKKKKKKKKK
	// KKKKKKKKKKKKKKKKKKKKOc''''''''',o0KKKKKKKKKKKKKK0o,'''''''''cOKKKKKKKKKKKKKKKKKKKK
	// KKKKKKKKKKKKKKKKKKKK0o,'''''''';x0KKKKKKKKKKKKKK0d;'''''''''lOKKKKKKKKKKKKKKKKKKKK
	// KKKKKKKKKKKKKKKKKKKKKOo;,'''',:d0KKKKKKKKKKKKKKKKOc,''''''':xKKKKKKKKKKKKKKKKKKKKK
	// KKKKKKKKKKKKKKKKKKKKKK0kdllloxO0KKKKKKKKKKKKKKKKKKOo;'''',ck0KKKKKKKKKKKKKKKKKKKKK
	// KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0kdoodk0KKKKKKKKKKKKKKKKKKKKKKK
	// XKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKX
	// XKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKX
	// NXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXN
	// WNKKKKKKKKKKKKKKKKKKKKK0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0KKKKKKKKKKKKKKKKKKKKKNW
	// MWXKKKKKKKKKKKKKKKKKK0xc::::::::::::::::::::::::::::::::::cx0KKKKKKKKKKKKKKKKKKXWM
	// MMWXKKKKKKKKKKKKKKKKK0o;'''''''''''''''''''''''''''''''''';o0KKKKKKKKKKKKKKKKKXWMM
	// MMMWXKKKKKKKKKKKKKKKKK0xddddddddddddddddddddddddddddddddddx0KKKKKKKKKKKKKKKKKXNMMM
	// MMMMWXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXWMMMM
	// MMMMMWXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXWMMMMM
	// MMMMMMWNXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKNWMMMMMM
	// MMMMMMMMWXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXWMMMMMMMM
	// MMMMMMMMMWNXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXNWMMMMMMMMM
	// MMMMMMMMMMMWNXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXWWMMMMMMMMMMM
	// MMMMMMMMMMMMMWWNXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXNWMMMMMMMMMMMMMM
	// MMMMMMMMMMMMMMMMWWNXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXNNWMMMMMMMMMMMMMMMM
	// MMMMMMMMMMMMMMMMMMMWWNXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXNWWMMMMMMMMMMMMMMMMMMM
	// MMMMMMMMMMMMMMMMMMMMMMMWWNNXXKKKKKKKKKKKKKKKKKKKKKKKKXXNNWWMMMMMMMMMMMMMMMMMMMMMMM
	// MMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNXXKKKKKKKKKKKKKKXXNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
}
